# Generated by Django 4.1.4 on 2022-12-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_dislike',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_like',
        ),
    ]
