# Generated by Django 4.1.4 on 2022-12-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_movie_movie_dislike_remove_movie_movie_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, to='main.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(default=0, help_text='указывать сумму в долларах'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_year',
            field=models.IntegerField(default=0),
        ),
    ]
