# Generated by Django 4.1.4 on 2022-12-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_movie_count_views_movie_slug'),
        ('main', '0007_movie_video'),
    ]

    operations = [
    ]
