# Generated by Django 4.1.4 on 2022-12-21 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_remove_movie_genre_movie_genre'),
        ('review', '0004_remove_rating_rating_alter_comment_movie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={},
        ),
        migrations.RemoveField(
            model_name='like',
            name='for_movie',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like_or_dislike',
        ),
        migrations.AddField(
            model_name='like',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movie_likes', to='main.movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
